added pre-qc-failed status filter
EBI-Metagenomics/emgapi-v2 pull request #24
Opened 2024-12-17 10:43 UTC by KateSakharova

2024-12-19 09:00 UTC, mberacochea commented on analyses/models.py
> +                cls.PRE_ASSEMBLY_QC_FAILED: False,
Pleae put "cls.PRE_ASSEMBLY_QC_FAILED: False," after "cls.ASSEMBLY_STARTED: False," :)

2024-12-19 09:03 UTC, mberacochea requested changes
Good catch.. not sure if we should rename the analyses QC to PRE-QC

2024-12-19 09:03 UTC, mberacochea commented on analyses/models.py
> +        ANALYSIS_PRE_QC_FAILED = "analysis_pre_qc_failed"
For analyses we don't have a "pre-qc".. it's just QC, right?

2024-12-19 09:03 UTC, mberacochea commented on workflows/flows/assemble_study.py
> +            f"status__{analyses.models.Assembly.AssemblyStates.PRE_ASSEMBLY_QC_FAILED}": False,
This one should go first; it doesn't change how it works—just improves readability

2025-01-03 13:48 UTC, SandyRogers approved these changes

2025-01-09 20:34 UTC, KateSakharova commented
@SandyRogers thank you, I will rebase from your branch!

2025-01-15 16:48 UTC, merged